Use $* instead of $@

diff --git a/pygshit b/pygshit
--- a/pygshit
+++ b/pygshit
@@ -4,7 +4,7 @@
 
 
 error(){
-    echo "ERROR: $@" >&2
+    echo "ERROR: $*" >&2
 }
 
 pygmentize(){
diff --git a/pygsparkle b/pygsparkle
--- a/pygsparkle
+++ b/pygsparkle
@@ -7,7 +7,7 @@
 VIEWER=ristretto
 
 error(){
-    echo "ERROR: $@" >&2
+    echo "ERROR: $*" >&2
 }
 
 handle-image(){
